### ISSUE TITLE
Feature request: Ignore Tasks

### ISSUE THREAD

**Issue by AntonTrapp** [sindresorhus/time-grunt#64] opened 2015-07-04 06:06 UTC
A way to ignore some tasks would be great. For example: The "watch" tasks takes hours to complete (because it is just waiting) and measuring the time there makes no sense.

**Comment by sindresorhus** [comment] 2015-07-04 09:46
Duplicate of #51. PR welcome :)

**Closed by sindresorhus** 2015-07-04 09:46 UTC

**Comment by AntonTrapp** [comment] 2015-07-04 10:31
Sorry, missed that. I am afraid that my grunt knowledge is much to low :(

**Comment by AdrianoCahete** [comment] 2016-05-31 19:41
#51 Just ignore `watch` task, not a list of tasks. 

A way to ignore some other tasks will be good too (notify task, for example).
